export PermGroup, trivialgroup, symmetricgroup, cyclicgroup, dihedralgroup,
       normalform


# This file might be useful if we decide to generalize the kinds of nominal sets 
# that we want to logically elaborate. Presently we assume our nominal set is 
# freely generated by a signature. But 

# Permutation groups on canonical supports
##########################################

# Every element explicit, rather than generators. A stabilizer-chain 
# representation could replace this if degrees ever grow.


"""
A group H ≤ Sₖ of permutations of the canonical support positions {1..k},
stored exhaustively in *one-line notation*.
"""
@struct_hash_equal struct PermGroup
  degree::Int
  elems::Set{Vector{Int}}

  function PermGroup(degree::Int, elems::Set{Vector{Int}})
    degree ≥ 0 || error("Bad degree $degree")
    collect(1:degree) ∈ elems || error("Missing identity permutation")
    for σ in elems
      (length(σ) == degree && isperm(σ)) ||
        error("Not a permutation of 1:$degree: $σ")
    end
    for σ in elems, τ in elems
      τ[σ] ∈ elems || error("Not closed under composition: $σ ⋆ $τ = $(τ[σ])")
    end
    new(degree, elems)
  end
end

"""
The subgroup ⟨gens⟩ ≤ Sₖ generated by closing `gens` under composition (which,
for finite sets of permutations, also yields identity and inverses).
"""
function PermGroup(degree::Int, gens::AbstractVector{<:AbstractVector{Int}})
  elems = Set{Vector{Int}}([collect(1:degree)])
  union!(elems, collect.(gens))
  while true
    frontier = Set{Vector{Int}}(τ[σ] for σ in elems, τ in elems)
    frontier ⊆ elems && break
    union!(elems, frontier)
  end
  PermGroup(degree, elems)
end

Base.in(σ::AbstractVector{Int}, H::PermGroup) = σ ∈ H.elems

Base.length(H::PermGroup) = length(H.elems)

Base.iterate(H::PermGroup, args...) = iterate(H.elems, args...)

Base.eltype(::Type{PermGroup}) = Vector{Int}

function Base.show(io::IO, ::MIME"text/plain", H::PermGroup)
  print(io, "PermGroup(deg $(H.degree), order $(length(H)))")
end

""" Is the group the trivial permutation """
istrivial(g::PermGroup) = length(g.elems) == 1 

issymmetric(g::PermGroup) = length(g.elems) == factorial(g.degree)

# Canonicalization
#-----------------

"""
Let `names` be an injection {1...k} ↣ 𝔸, whose elements are of type `T`.

`normalform` returns lexicographically least tuple obtainable by permuting 
`names` by an element of H. E.g. `normalform([:c,:a,:b], C₃) = [:a,:b,:c]`.
"""
function normalform(names::AbstractVector{T}, H::PermGroup)::Vector{T} where T 
  @assert allunique(names)
  @assert length(names) == H.degree
  minimum(names[σ] for σ in H.elems)
end

""" 
One representative per left coset σH of H in Sₖ. This is the distinct ways of
loading k names into argument positions, up to the stabilizer.
"""
transversal(H::PermGroup) =
  unique(σ -> normalform(σ, H), collect(permutations(1:H.degree)))


# Named subgroups
#----------------

""" H = {id} """
trivialgroup(k::Int) = PermGroup(k, Set([collect(1:k)]))

""" 
H = Sₖ, all k! permutations
"""
symmetricgroup(k::Int) =
  PermGroup(k, Set{Vector{Int}}(permutations(collect(1:k))))

""" H = Cₖ, the k rotations i ↦ i+j (mod k) """
cyclicgroup(k::Int) = k ≤ 1 ? trivialgroup(k) :
  PermGroup(k, Set{Vector{Int}}([[mod(i + j - 1, k) + 1 for i in 1:k]
                                 for j in 0:k-1]))

"""
H = Dₖ≅ Cₖ ⋊ C₂ of order 2k, the symmetries of a regular k-gon. Every symmetry
factors *uniquely* as a rotation optionally followed by the reflection
s = (i ↦ k+1-i), so the underlying set is just {rⱼ} ∪ {rⱼ then s}. 

For k ≤ 2 the k-gon degenerates: rotation and reflection coincide as
permutations of the vertices, and Dₖ collapses to Sₖ.
"""
function dihedralgroup(k::Int)
  k ≤ 2 && return symmetricgroup(k)
  rotations = cyclicgroup(k).elems
  s = reverse(collect(1:k))
  PermGroup(k, union(rotations, Set{Vector{Int}}(s[ρ] for ρ in rotations)))
end

